# -*- coding: utf-8 -*-
"""Gol Contaduría.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSCl9nqRpJnxsUEj9wPaXPnaAjDbdjPU
"""

import streamlit as st
import random

st.set_page_config(page_title="Un gol por la Contaduría", page_icon="⚽")

st.title("⚽ Un gol por la Contaduría")
st.subheader("Responde correctamente y gana tu oportunidad de gol")

# Banco de preguntas
preguntas = [
    {
        "pregunta": "¿Qué es un activo?",
        "opciones": ["Un gasto", "Un recurso controlado por la empresa", "Una deuda", "Un ingreso"],
        "respuesta": "Un recurso controlado por la empresa"
    },
    {
        "pregunta": "¿Qué representa el pasivo?",
        "opciones": ["Ingresos", "Deudas y obligaciones", "Activos", "Capital"],
        "respuesta": "Deudas y obligaciones"
    },
    {
        "pregunta": "¿Qué es el capital contable?",
        "opciones": ["Deudas", "Aportaciones de socios y utilidades", "Gastos", "Ventas"],
        "respuesta": "Aportaciones de socios y utilidades"
    },
    {
        "pregunta": "¿Cuál es la ecuación contable básica?",
        "opciones": [
            "Activo = Pasivo + Capital",
            "Activo = Ingreso - Gasto",
            "Capital = Activo - Pasivo",
            "Pasivo = Activo + Capital"
        ],
        "respuesta": "Activo = Pasivo + Capital"
    },
    {
        "pregunta": "¿Qué es un ingreso?",
        "opciones": ["Salida de dinero", "Aumento en beneficios económicos", "Deuda", "Activo fijo"],
        "respuesta": "Aumento en beneficios económicos"
    },
    {
        "pregunta": "¿Qué es un gasto?",
        "opciones": ["Ingreso", "Disminución de beneficios económicos", "Activo", "Capital"],
        "respuesta": "Disminución de beneficios económicos"
    },
    {
        "pregunta": "¿Qué es depreciación?",
        "opciones": ["Aumento del valor", "Distribución del costo de un activo", "Ingreso", "Pasivo"],
        "respuesta": "Distribución del costo de un activo"
    },
    {
        "pregunta": "¿Qué es un balance general?",
        "opciones": ["Estado financiero", "Registro de ventas", "Libro diario", "Factura"],
        "respuesta": "Estado financiero"
    },
    {
        "pregunta": "¿Qué muestra el estado de resultados?",
        "opciones": ["Activos", "Utilidad o pérdida", "Deudas", "Capital"],
        "respuesta": "Utilidad o pérdida"
    },
    {
        "pregunta": "¿Qué es el IVA?",
        "opciones": ["Impuesto al valor agregado", "Ingreso", "Gasto", "Activo"],
        "respuesta": "Impuesto al valor agregado"
    },
    {
        "pregunta": "¿Qué es una cuenta contable?",
        "opciones": ["Registro de operaciones", "Factura", "Balance", "Ingreso"],
        "respuesta": "Registro de operaciones"
    },
    {
        "pregunta": "¿Qué es el libro diario?",
        "opciones": ["Registro cronológico", "Balance", "Ingreso", "Activo"],
        "respuesta": "Registro cronológico"
    },
    {
        "pregunta": "¿Qué es el libro mayor?",
        "opciones": ["Clasificación de cuentas", "Ingreso", "Factura", "Gasto"],
        "respuesta": "Clasificación de cuentas"
    },
    {
        "pregunta": "¿Qué es liquidez?",
        "opciones": ["Capacidad de pago a corto plazo", "Deuda", "Activo fijo", "Ingreso"],
        "respuesta": "Capacidad de pago a corto plazo"
    },
    {
        "pregunta": "¿Qué es solvencia?",
        "opciones": ["Capacidad de pago a largo plazo", "Ingreso", "Gasto", "Activo"],
        "respuesta": "Capacidad de pago a largo plazo"
    },
    {
        "pregunta": "¿Qué es inventario?",
        "opciones": ["Bienes para venta", "Ingreso", "Pasivo", "Capital"],
        "respuesta": "Bienes para venta"
    },
    {
        "pregunta": "¿Qué es costo de ventas?",
        "opciones": ["Costo de productos vendidos", "Ingreso", "Activo", "Capital"],
        "respuesta": "Costo de productos vendidos"
    },
    {
        "pregunta": "¿Qué es utilidad?",
        "opciones": ["Ganancia", "Deuda", "Activo", "Gasto"],
        "respuesta": "Ganancia"
    },
    {
        "pregunta": "¿Qué es pérdida?",
        "opciones": ["Disminución de capital", "Ingreso", "Activo", "Pasivo"],
        "respuesta": "Disminución de capital"
    },
    {
        "pregunta": "¿Qué es flujo de efectivo?",
        "opciones": ["Movimiento de dinero", "Activo", "Pasivo", "Capital"],
        "respuesta": "Movimiento de dinero"
    }
]

# Retos
retos = [
    "I) ⚽ Desde tres metros, anotar el gol de taquito",
    "II) ⚽ Desde cuatro metros, con los ojos vendados",
    "III) ⚽ Desde seis metros, girar tres veces a la derecha y tres a la izquierda"
]

# Estado de sesión
if "pregunta_actual" not in st.session_state:
    st.session_state.pregunta_actual = random.choice(preguntas)
    st.session_state.respondido = False

pregunta = st.session_state.pregunta_actual

st.write("### Pregunta:")
st.write(pregunta["pregunta"])

respuesta_usuario = st.radio("Selecciona tu respuesta:", pregunta["opciones"])

if st.button("Responder"):
    st.session_state.respondido = True

    if respuesta_usuario == pregunta["respuesta"]:
        st.success("✅ ¡Correcto!")
        reto = random.choice(retos)
        st.subheader("🎯 Tu reto es:")
        st.warning(reto)
    else:
        st.error("❌ Incorrecto. ¡Sigue intentando!")

if st.button("Nueva pregunta"):
    st.session_state.pregunta_actual = random.choice(preguntas)
    st.session_state.respondido = False
    st.rerun()